name: polaris upload and scan
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: NodeGoat
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Run Polaris Scan
        shell: bash
        env:
          POLARIS_API_URL: ${{ secrets.POLARIS_API_URL }}
          POLARIS_API_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          POLARIS_APP_NAME: ${{ secrets.POLARIS_APP_NAME }}
          POLARIS_PROJECT_NAME: ${{ secrets.POLARIS_PROJECT_NAME }}
          POLARIS_SCA_ENTITLEMENT: ${{ secrets.POLARIS_SCA_ENTITLEMENT }}
          POLARIS_SAST_ENTITLEMENT: ${{ secrets.POLARIS_SAST_ENTITLEMENT }}
        run: |
        pip3 install -y -r requirements.txt \
          python3 .polaris-uploadandscan.py \
          rm -rf polarispackage.zip \
