name: polaris upload and scan
on: [push, pull_request]
jobs:
  run:
    name: Build NodeGoat
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64
      - name: Run tests
        run: npm install
      - name: Run Polaris Scan
        shell: bash
        env:
          BRIDGE_POLARIS_SERVERURL: ${{ secrets.POLARIS_SERVER_URL }}
          BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          BRIDGE_POLARIS_APPLICATION_NAME: "JP-insecurebank"
          BRIDGE_POLARIS_PROJECT_NAME: "insecurebank-gh-pr"
          BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
        run: |
        echo "$BRIDGECLI_LINUX64"
        echo "$BRIDGE_POLARIS_SERVERURL"
        echo "$RUNNER_TEMP"
        #curl -fLsS -o bridge.zip https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/1.1.0/synopsys-bridge-1.1.0-linux64.zip && unzip -qo -d $RUNNER_TEMP bridge.zip && rm -f bridge.zip
        #$RUNNER_TEMP/synopsys-bridge --verbose --stage polaris polaris.assessment.types=SAST,SCA --input input.json
