name: polaris upload and scan
on: [push, pull_request]

jobs:
  e2e-test:
    name: Node.js
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["10.x", "12.x", "14.x"]
